### Create a new user

POST http://localhost:3000/users/new
Content-Type: application/json

{    
    "email":"gulshan",
    "password":"1234"
}
### find all users
GET http://localhost:3000/users/person
Content-Type: application/json


### Hello world
GET http://localhost:3000